# Generated by Django 5.0.2 on 2024-02-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_event_zoom_url_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zoom_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
